# NumPy DataTypes

In [1]:
import numpy as np

### 1. With the help of the <i> np.array() </i>function, create a 1-D array variable <i> array_hw_1 </i> with the numbers from 1 to 8 and display it on the screen.

In [2]:
array_hw_1 = np.array([1, 2, 3, 4, 5, 6, 7, 8])
array_hw_1

array([1, 2, 3, 4, 5, 6, 7, 8])

### 2.Check its type, shape and size. 
<i> (<b>Hint </b>: "type" is a Python function, while "shape" and "size" are attributes of the array) </i>

In [3]:
type(array_hw_1)

numpy.ndarray

In [4]:
array_hw_1.shape

(8,)

In [5]:
array_hw_1.size

8

### 3. Now, create a 2x4 2-D array, <i> array_hw_2</i> with the same values & display it on screen. 

In [6]:
array_hw_2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
array_hw_2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### 4. Find its type, shape, and size. 

In [7]:
type(array_hw_2)

numpy.ndarray

In [8]:
array_hw_2.shape

(2, 4)

In [9]:
array_hw_2.size

8

### 5. Use square brackets to create a 3-D array with the same values as <i> array_hw_2 </i> and display it on screen.

In [10]:
array_hw_3 = np.array([array_hw_2, array_hw_2])
array_hw_3

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[1, 2, 3, 4],
        [5, 6, 7, 8]]])

### 6. Find its type, shape and size. 


In [11]:
type(array_hw_3)

numpy.ndarray

In [12]:
array_hw_3.shape

(2, 2, 4)

In [13]:
array_hw_3.size

16

### 7. Define a 2-D list <i> list_hw_1 </i> with the same values as <i> array_hw_2 </i>and display it on screen.

In [14]:
list_hw_1 = [[1, 2, 3, 4], [5, 6, 7, 8]]
list_hw_1

[[1, 2, 3, 4], [5, 6, 7, 8]]

### 8. Find the length of this 2-D list. 

In [15]:
len(list_hw_1)

2

### 9. Fint the length of one of its sublists. 

In [16]:
len(list_hw_1[0])

4

### 10. Verify its type. 

In [17]:
type(list_hw_1)

list

### 11. Use the <i>np.array()</i> function to create an array out of <i> list_hw_1</i> and display it on screen.

In [18]:
array_hw_2 = np.array(list_hw_1)

In [19]:
array_hw_2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### 12. Create two more variables and display them on screen:
    A) A list which is the sum of the two sublists of list_hw_1;
    B) An array which is the sum of the two subarrays of array_hw_4;
    
    (Hint: Use indexing to refer to the different sub-lists/arrays)

In [20]:
list_hw_2 = list_hw_1[0] + list_hw_1[1]

In [21]:
list_hw_2

[1, 2, 3, 4, 5, 6, 7, 8]

In [22]:
array_hw_4 = array_hw_3[0] + array_hw_3[1]

In [23]:
array_hw_4

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

### 13. Find the square roots of all the elements in <i> array_sum </i>
   <i> (<b>Hint</b>: Use the np.sqrt() function)

In [24]:
np.sqrt(array_hw_4)

array([[1.41421356, 2.        , 2.44948974, 2.82842712],
       [3.16227766, 3.46410162, 3.74165739, 4.        ]])

### 13. Find the square roots of all the elements in <i> list_sum </i>
   <i> (<b>Hint</b>: Most NumPy functions are equipped to handle <b> lists </b>like ndarrays with the same shape)

In [25]:
#import math
#array_e = math.sqrt(list_hw_2)      
#print(array_e)
# all the above gave error
np.sqrt(list_hw_2)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712])

### 14. Use <i> np.genfromtxt() </i> to import the <i> "Lending-Company-Total-Price.csv" </i> file as strings and display its contents.
    You can open the file in a text editor like Notepad++ to check its delimiter. 

In [26]:
lending_co_total_price = np.genfromtxt("Lending-Company-Total-Price.csv", 
                                        delimiter = ',',
                                        dtype = str)
lending_co_total_price

array([['LoanID', 'StringID', 'Product', ..., 'Location', 'Region',
        'TotalPrice'],
       ['1', 'id_1', 'Product B', ..., 'Location 2', 'Region 2', '16600'],
       ['2', 'id_2', 'Product B', ..., 'Location 3', '', '16600'],
       ...,
       ['413', 'id_413', 'Product B', ..., 'Location 135', 'Region 1',
        '16600'],
       ['414', 'id_414', 'Product C', ..., 'Location 200', 'Region 6',
        '15600'],
       ['415', 'id_415', 'Product A', ..., 'Location 8', 'Region 2',
        '22250']], dtype='<U14')

### 15. Use the <i> skip_header </i> and <i> usecols </i> parameters to only take the numerical data from the file. Then, let's see how the inputs change if we alter the datatype argument to:

    A) The default (not specify it)
    B) 32-bit integers (np.int32)
    C) 32-bit floats (np.float32)
    D) 64-bit complex numbers (np.complex64)
    E) Unicode (np.unicode)
    F) Objects (np.object)
    G) None

In [27]:
lending_co_total_price = np.genfromtxt("Lending-Company-Total-Price.csv", 
                                        delimiter = ',',
                                        skip_header = 1,
                                        usecols = (0, -1))
lending_co_total_price

array([[1.0000e+00, 1.6600e+04],
       [2.0000e+00, 1.6600e+04],
       [3.0000e+00, 1.5600e+04],
       [4.0000e+00, 1.6600e+04],
       [5.0000e+00, 2.0250e+04],
       [6.0000e+00,        nan],
       [7.0000e+00, 2.0250e+04],
       [8.0000e+00, 1.6600e+04],
       [9.0000e+00, 2.2250e+04],
       [1.0000e+01, 2.0250e+04],
       [1.1000e+01, 1.6600e+04],
       [1.2000e+01, 2.0250e+04],
       [1.3000e+01, 1.6600e+04],
       [1.4000e+01, 2.0750e+04],
       [1.5000e+01, 2.2250e+04],
       [1.6000e+01, 1.6600e+04],
       [1.7000e+01, 2.2250e+04],
       [1.8000e+01, 1.6600e+04],
       [1.9000e+01, 1.6600e+04],
       [2.0000e+01, 5.4625e+04],
       [2.1000e+01, 1.6600e+04],
       [2.2000e+01, 2.2250e+04],
       [2.3000e+01, 1.9250e+04],
       [2.4000e+01, 1.5600e+04],
       [2.5000e+01, 2.0250e+04],
       [2.6000e+01, 2.2250e+04],
       [2.7000e+01, 1.9250e+04],
       [2.8000e+01, 6.9225e+04],
       [2.9000e+01, 2.0250e+04],
       [3.0000e+01, 1.6600e+04],
       [3.

In [28]:
lending_co_total_price = np.genfromtxt("Lending-Company-Total-Price.csv", 
                                        delimiter = ',',
                                        dtype = np.int32,
                                        skip_header = 1,
                                        usecols = (0, -1))
lending_co_total_price

array([[    1, 16600],
       [    2, 16600],
       [    3, 15600],
       [    4, 16600],
       [    5, 20250],
       [    6,    -1],
       [    7, 20250],
       [    8, 16600],
       [    9, 22250],
       [   10, 20250],
       [   11, 16600],
       [   12, 20250],
       [   13, 16600],
       [   14, 20750],
       [   15, 22250],
       [   16, 16600],
       [   17, 22250],
       [   18, 16600],
       [   19, 16600],
       [   20, 54625],
       [   21, 16600],
       [   22, 22250],
       [   23, 19250],
       [   24, 15600],
       [   25, 20250],
       [   26, 22250],
       [   27, 19250],
       [   28, 69225],
       [   29, 20250],
       [   30, 16600],
       [   31, 16600],
       [   32, 16600],
       [   33, 19250],
       [   34, 16600],
       [   35, 19250],
       [   36, 16600],
       [   37, 16600],
       [   38, 16600],
       [   39, 15600],
       [   40, 16600],
       [   41, 16600],
       [   42, 16600],
       [   43, 19250],
       [   

In [29]:
lending_co_total_price = np.genfromtxt("Lending-Company-Total-Price.csv", 
                                        delimiter = ',',
                                        dtype = np.float32,
                                        skip_header = 1,
                                        usecols = (0, -1))
lending_co_total_price

array([[1.0000e+00, 1.6600e+04],
       [2.0000e+00, 1.6600e+04],
       [3.0000e+00, 1.5600e+04],
       [4.0000e+00, 1.6600e+04],
       [5.0000e+00, 2.0250e+04],
       [6.0000e+00,        nan],
       [7.0000e+00, 2.0250e+04],
       [8.0000e+00, 1.6600e+04],
       [9.0000e+00, 2.2250e+04],
       [1.0000e+01, 2.0250e+04],
       [1.1000e+01, 1.6600e+04],
       [1.2000e+01, 2.0250e+04],
       [1.3000e+01, 1.6600e+04],
       [1.4000e+01, 2.0750e+04],
       [1.5000e+01, 2.2250e+04],
       [1.6000e+01, 1.6600e+04],
       [1.7000e+01, 2.2250e+04],
       [1.8000e+01, 1.6600e+04],
       [1.9000e+01, 1.6600e+04],
       [2.0000e+01, 5.4625e+04],
       [2.1000e+01, 1.6600e+04],
       [2.2000e+01, 2.2250e+04],
       [2.3000e+01, 1.9250e+04],
       [2.4000e+01, 1.5600e+04],
       [2.5000e+01, 2.0250e+04],
       [2.6000e+01, 2.2250e+04],
       [2.7000e+01, 1.9250e+04],
       [2.8000e+01, 6.9225e+04],
       [2.9000e+01, 2.0250e+04],
       [3.0000e+01, 1.6600e+04],
       [3.

In [30]:
lending_co_total_price = np.genfromtxt("Lending-Company-Total-Price.csv", 
                                        delimiter = ',',
                                        dtype = np.complex64,
                                        skip_header = 1,
                                        usecols = (0, -1))
lending_co_total_price

array([[1.0000e+00+0.j, 1.6600e+04+0.j],
       [2.0000e+00+0.j, 1.6600e+04+0.j],
       [3.0000e+00+0.j, 1.5600e+04+0.j],
       [4.0000e+00+0.j, 1.6600e+04+0.j],
       [5.0000e+00+0.j, 2.0250e+04+0.j],
       [6.0000e+00+0.j,        nan+0.j],
       [7.0000e+00+0.j, 2.0250e+04+0.j],
       [8.0000e+00+0.j, 1.6600e+04+0.j],
       [9.0000e+00+0.j, 2.2250e+04+0.j],
       [1.0000e+01+0.j, 2.0250e+04+0.j],
       [1.1000e+01+0.j, 1.6600e+04+0.j],
       [1.2000e+01+0.j, 2.0250e+04+0.j],
       [1.3000e+01+0.j, 1.6600e+04+0.j],
       [1.4000e+01+0.j, 2.0750e+04+0.j],
       [1.5000e+01+0.j, 2.2250e+04+0.j],
       [1.6000e+01+0.j, 1.6600e+04+0.j],
       [1.7000e+01+0.j, 2.2250e+04+0.j],
       [1.8000e+01+0.j, 1.6600e+04+0.j],
       [1.9000e+01+0.j, 1.6600e+04+0.j],
       [2.0000e+01+0.j, 5.4625e+04+0.j],
       [2.1000e+01+0.j, 1.6600e+04+0.j],
       [2.2000e+01+0.j, 2.2250e+04+0.j],
       [2.3000e+01+0.j, 1.9250e+04+0.j],
       [2.4000e+01+0.j, 1.5600e+04+0.j],
       [2.5000e+

In [31]:
lending_co_total_price = np.genfromtxt("Lending-Company-Total-Price.csv", 
                                        delimiter = ',',
                                        dtype = np.compat.unicode,
                                        skip_header = 1,
                                        usecols = (0, -1))
lending_co_total_price

array([['1', '16600'],
       ['2', '16600'],
       ['3', '15600'],
       ['4', '16600'],
       ['5', '20250'],
       ['6', ''],
       ['7', '20250'],
       ['8', '16600'],
       ['9', '22250'],
       ['10', '20250'],
       ['11', '16600'],
       ['12', '20250'],
       ['13', '16600'],
       ['14', '20750'],
       ['15', '22250'],
       ['16', '16600'],
       ['17', '22250'],
       ['18', '16600'],
       ['19', '16600'],
       ['20', '54625'],
       ['21', '16600'],
       ['22', '22250'],
       ['23', '19250'],
       ['24', '15600'],
       ['25', '20250'],
       ['26', '22250'],
       ['27', '19250'],
       ['28', '69225'],
       ['29', '20250'],
       ['30', '16600'],
       ['31', '16600'],
       ['32', '16600'],
       ['33', '19250'],
       ['34', '16600'],
       ['35', '19250'],
       ['36', '16600'],
       ['37', '16600'],
       ['38', '16600'],
       ['39', '15600'],
       ['40', '16600'],
       ['41', '16600'],
       ['42', '16600'],
      

In [32]:
lending_co_total_price = np.genfromtxt("Lending-Company-Total-Price.csv", 
                                        delimiter = ',',
                                        dtype = object,
                                        skip_header = 1,
                                        usecols = (0, -1))
lending_co_total_price

array([[b'1', b'16600'],
       [b'2', b'16600'],
       [b'3', b'15600'],
       [b'4', b'16600'],
       [b'5', b'20250'],
       [b'6', b''],
       [b'7', b'20250'],
       [b'8', b'16600'],
       [b'9', b'22250'],
       [b'10', b'20250'],
       [b'11', b'16600'],
       [b'12', b'20250'],
       [b'13', b'16600'],
       [b'14', b'20750'],
       [b'15', b'22250'],
       [b'16', b'16600'],
       [b'17', b'22250'],
       [b'18', b'16600'],
       [b'19', b'16600'],
       [b'20', b'54625'],
       [b'21', b'16600'],
       [b'22', b'22250'],
       [b'23', b'19250'],
       [b'24', b'15600'],
       [b'25', b'20250'],
       [b'26', b'22250'],
       [b'27', b'19250'],
       [b'28', b'69225'],
       [b'29', b'20250'],
       [b'30', b'16600'],
       [b'31', b'16600'],
       [b'32', b'16600'],
       [b'33', b'19250'],
       [b'34', b'16600'],
       [b'35', b'19250'],
       [b'36', b'16600'],
       [b'37', b'16600'],
       [b'38', b'16600'],
       [b'39', b'15600'],


In [33]:
lending_co_total_price = np.genfromtxt("Lending-Company-Total-Price.csv", 
                                        delimiter = ',',
                                        dtype = None,
                                        skip_header = 1,
                                        usecols = (0, -1))
lending_co_total_price

array([[    1, 16600],
       [    2, 16600],
       [    3, 15600],
       [    4, 16600],
       [    5, 20250],
       [    6,    -1],
       [    7, 20250],
       [    8, 16600],
       [    9, 22250],
       [   10, 20250],
       [   11, 16600],
       [   12, 20250],
       [   13, 16600],
       [   14, 20750],
       [   15, 22250],
       [   16, 16600],
       [   17, 22250],
       [   18, 16600],
       [   19, 16600],
       [   20, 54625],
       [   21, 16600],
       [   22, 22250],
       [   23, 19250],
       [   24, 15600],
       [   25, 20250],
       [   26, 22250],
       [   27, 19250],
       [   28, 69225],
       [   29, 20250],
       [   30, 16600],
       [   31, 16600],
       [   32, 16600],
       [   33, 19250],
       [   34, 16600],
       [   35, 19250],
       [   36, 16600],
       [   37, 16600],
       [   38, 16600],
       [   39, 15600],
       [   40, 16600],
       [   41, 16600],
       [   42, 16600],
       [   43, 19250],
       [   

### 16. Setting the datatype to None means the function automatically chooses the datatype for each column of the text file, so let's see how this works for all the columns.

In [34]:
lending_co_total_price = np.genfromtxt("Lending-Company-Total-Price.csv", 
                                        delimiter = ',',
                                        dtype = None,
                                        skip_header = 1)
lending_co_total_price

C:\Users\Dawodu Oluwafikayo\AppData\Local\Temp\ipykernel_14020\3954970212.py:1: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  lending_co_total_price = np.genfromtxt("Lending-Company-Total-Price.csv",


array([(  1, b'id_1', b'Product B', b'Male', b'Location 2', b'Region 2', 16600),
       (  2, b'id_2', b'Product B', b'Male', b'Location 3', b'', 16600),
       (  3, b'id_3', b'Product C', b'Female', b'Location 5', b'Region 5', 15600),
       (  4, b'id_4', b'Product B', b'Male', b'Location 6', b'Region 1', 16600),
       (  5, b'id_5', b'Product D', b'Female', b'Location 7', b'Region 2', 20250),
       (  6, b'id_6', b'Product B', b'Female', b'Location 10', b'Region 2',    -1),
       (  7, b'id_7', b'Product A', b'Male', b'Location 11', b'Region 3', 20250),
       (  8, b'id_8', b'Product B', b'Male', b'Location 12', b'Region 6', 16600),
       (  9, b'id_9', b'Product A', b'Female', b'Location 3', b'Region 3', 22250),
       ( 10, b'id_10', b'Product A', b'Female', b'Location 13', b'Region 6', 20250),
       ( 11, b'id_11', b'Product B', b'Female', b'Location 15', b'Region 2', 16600),
       ( 12, b'id_12', b'Product D', b'Female', b'Location 16', b'Region 1', 20250),
       ( 13, 